### ISSUE TITLE
DX and Clean Code: Peer review

### ISSUE THREAD

**Issue by stenvma81** [pennane/chess#2]
***Application Overview Understanding***

Nice and informative Readme. The goal of the project is clear. The folder structure also seems quite logical. 

***Code Structure and Quality***

The code is well structured overall. It is split into logical components and there is no bloat or clearly unnecessary nesting.

On the naming side there are some not so self explanatory choices. The naming of the chess constants could be more descriptive (not using just a single character), but looking at the fen strings it's easy to see why they are named as they are. It might not be super easy to follow for someone not versed in coding (or chess).

In general, the naming is done well and as far as I can tell, the functions are structured nicely. The code can seem a bit technical at times so maybe changing the naming to... Err... "Idiotproof" might be a good idea.

***Commit Analysis***

The commit messages are clear but don't really go deep into the what and why.  I would actually like to hear more about your way of describing commits as there clearly is a method to it. As it is, the partial technicality of the code could use more explanatory commit messages.

***Communication and Documentation***

The documentation is up to par and explains the project well.

***Suggestions for Improvement***

- The commit messages could use more emphasis. Explaining what was done and why, even with a few words, would help a random viewer to understand the project timeline from just looking at the commit list.
- I personally like the way the code is structured and written, but some spots could use a bit more clarification, mainly in naming. But then again it could probably kinda break the overall flow of the code. Hm. Not easy to apply DX when the code gets even a tad more technical.
- Some of the files could use more descriptive names.

**Comment by pennane** [comment]
Thanks for the review. I agree with your critique. It is a nice challenge to turn technical problems into something readable.
