### ISSUE TITLE
DX and Clean Code, Week 3, Peer Review

### ISSUE THREAD

**Issue by w1000w** [pennane/chess#4]
## Application Overview Understanding

The purpose of the application is to create a web-based chess game where you play against the computer (or watch a computer play against another computer). Project structure makes sense with the UI and game logic separated into their own folders. There's some
domain specific language like "fen" that's not immediately clear, but there are comments in the code to explain the terminology and clear these up.

The code is for the most part clear and well thought out, communicating it's purpose clearly enough. 

## Code Structure and Quality

Naming is mostly fine, again, there's some domain specific language, but you get the gist with a bit of Googling. Some of the functions are a bit large and can get hard to read because of the number of conditions, but this problem seems to be almost unavoidable when dealing with game logic of any type.

Overall, the code flows logically and is well structured.

## Commit Analysis

Most of the commits are properly sized and self-contained. Commit messages are clear and understandable, but there are few commits that are large in size and quite general in their message. There's one for example called "large refactor" where it's hard to decipher what's been done  just because of the sheer size of the changes (apart from the obvious large refactoring).

## Communication and Documentation

The README is clear, you easily get an understanding of what the project does. The image is a nice addition, giving you an idea on what to expect. Instructions for running the program are clear and I was able to get it
successfully running without a hitch. 

## Suggestions for Improvement

- Avoid larger commits. Also, 'why?' in addition to the 'what?'.
- Maybe think of introducing some named helper functions to break down some of the larger ones.

**Comment by pennane** [comment]
Good comments. I agree. Good point that commit messages should most likely have a "why?" in them.
